# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dnsrecon = {
    pname = "dnsrecon";
    version = "13c47504dedd4203610f407ef9619fc085a2df97";
    src = fetchgit {
      url = "https://github.com/darkoperator/dnsrecon";
      rev = "13c47504dedd4203610f407ef9619fc085a2df97";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pT2TEOqSmnjp/r0E72W3nFolkrM+Fec+iJGD1MptRcc=";
    };
    date = "2026-10-09";
  };
  garak = {
    pname = "garak";
    version = "105164ba3f7960954cf69fb81a610fe672197eb0";
    src = fetchgit {
      url = "https://github.com/NVIDIA/garak";
      rev = "105164ba3f7960954cf69fb81a610fe672197eb0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Z71oeb5DrHT/qIgYE3HID8yWlAcp5CVSVmHNBm+eb3A=";
    };
    date = "2026-10-09";
  };
  pyrit = {
    pname = "pyrit";
    version = "f916d8ee5df7b2e9859ff2c1ffef596d993db0d2";
    src = fetchgit {
      url = "https://github.com/Microsoft/PyRIT";
      rev = "f916d8ee5df7b2e9859ff2c1ffef596d993db0d2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lsTTcDrMx66yqen7jiTL8O3n6Mq/chkq1LL8hwVO/vE=";
    };
    date = "2026-10-10";
  };
  subfinder = {
    pname = "subfinder";
    version = "c97f25802892093060f0fc424bfc3f39e273693a";
    src = fetchgit {
      url = "https://github.com/projectdiscovery/subfinder";
      rev = "c97f25802892093060f0fc424bfc3f39e273693a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-O1Er4Ep3kiYcswaHf0bxcmG2OysHm/j58uC5BXA4qLU=";
    };
    date = "2026-10-08";
  };
}
