# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  dnsrecon = {
    pname = "dnsrecon";
    version = "13c47504dedd4203610f407ef9619fc085a2df97";
    src = fetchgit {
      url = "https://github.com/darkoperator/dnsrecon";
      rev = "13c47504dedd4203610f407ef9619fc085a2df97";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pT2TEOqSmnjp/r0E72W3nFolkrM+Fec+iJGD1MptRcc=";
    };
    date = "2026-10-09";
  };
  subfinder = {
    pname = "subfinder";
    version = "c97f25802892093060f0fc424bfc3f39e273693a";
    src = fetchgit {
      url = "https://github.com/projectdiscovery/subfinder";
      rev = "c97f25802892093060f0fc424bfc3f39e273693a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-O1Er4Ep3kiYcswaHf0bxcmG2OysHm/j58uC5BXA4qLU=";
    };
    date = "2026-10-08";
  };
}
